// Code generated by MockGen. DO NOT EDIT.
// Source: application\product\service.go

// Package product_mock is a generated GoMock package.
package product_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	product "github.com/samuelemwangi/jumia-mds-test/services/bulkupdates/application/product"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// SaveProduct mocks base method.
func (m *MockProductService) SaveProduct(arg0, arg1 string) (*product.ProductItemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProduct", arg0, arg1)
	ret0, _ := ret[0].(*product.ProductItemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProduct indicates an expected call of SaveProduct.
func (mr *MockProductServiceMockRecorder) SaveProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProduct", reflect.TypeOf((*MockProductService)(nil).SaveProduct), arg0, arg1)
}
